version: '2'
services:
  el-life-tracker:
    image: elasticsearch:5.4.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    command: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:5.4.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://el-life-tracker:9200
    links:
      - el-life-tracker
